version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: paoo
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
